### ISSUE TITLE
lapYear evaluation is missing an equal sign

### ISSUE THREAD

**Issue by tobozo** [deruiter/DCF77-Analyzer-Clock#2]
Hello Mr De Ruiter

your design is so good I'm porting it to a small TFT display, while doing that I noticed a tiny typo in the source code :

https://github.com/deruiter/DCF77-Analyzer-Clock-V2.0/blob/fe2abf0495169203b5e177e568e68616adc71c21/Arduino%20Sketches/DCF77_Analyzer_Clock_2_0_Main_sketch/DCF77_Analyzer_Clock_2_0_Main_sketch.ino#L1713

should read:

```c
    if (leapYear == 1)
```

**Comment by deruiter** [comment]
wow, thank you very much!  I forgot to correct this error, sorry about that...!
I don't know how to give you credit here but many thanks...
Erik

**Comment by tobozo** [comment]
Thanks to you I had much fun working on your code to get it working, now I'm the one giving you credits here : https://youtu.be/V3Gqdkv7T00

Would that be okay if I published the modified code? 

If so, please let me know if you prefer a standalone/detached project to a fork attached to your repository.

I can also validate the credits/license with you before making it public.

**Comment by tobozo** [comment]
hey ^^ I just published the TFT version here https://github.com/tobozo/esp32-DCF77_Analyzer_Clock

please let me know if you need me to make modifications (license, credits), I've tried my best to put every bits but I'm only human :-)

**Comment by deruiter** [comment]
Hello Tobozo,
Sorry, I forgot to reply to your previous email...
WOW what an amazig clock you made!!!  
Thank you for letting me know, no need for modifications, thanks for the credits although it's all open source.
Now i want to make your version also! ;)
I have to look at your code to learn new things... The DCF Clock was my first Arduino project so it has lots to be desired but it at least did work...
Thanks again!
Erik

**Comment by tobozo** [comment]
I've added the support for the weather, still very basic though.

**Comment by deruiter** [comment]
> I've added the support for the weather, still very basic though.

This is great as it is...!
If you are OK with it, I can add your version of the clock on my Hackster project page?

**Comment by tobozo** [comment]
of course I'm ok with it :-) 

I'm playing with the UI anyway, I'm not sure yet what will happen when the app will load in a M5Stack or Odroid-Go but 320*240 offers much more space, and this could be used to display the weather data in a more comprehensive way.

**Comment by deruiter** [comment]
Done, added your clock URL at the end of the page under 'Take a look' header...
Great work!
