### ISSUE TITLE
Switches without connections ?

### ISSUE THREAD

**Issue by Bertusdejong** [deruiter/DCF77-Analyzer-Clock#4]
Hi Erik,
Great project. I just -nearly- finished building it. I came across some issues:
Unable to find how to connect the Option 1and Option 2 Switches.
Can't find either how to connect the power save switch (from the code I see it has to be connected to pin 6 . But the code itself doesnot show any readout of this pin).
Hope you can help me out on this!
Thanks in advance

**Comment by deruiter** [comment]
Hello Bertus!
See my email sent to you, issue is fixed...
new code on my Hackster.io/edr1924 page...

option 1 and 2 switches are not in use yet...
